Initial Setup
devslane/vite-react-redux-tailwind-boilerplate pull request #1
Opened 2022-03-17 12:03 UTC by madhav-devslane

2022-03-21 10:21 UTC, kush-prof requested changes

2022-03-21 10:21 UTC, kush-prof commented on src/models/entities/entity.ts
> +  id: number;
@madhav-devslane Same reference from [this comment](https://github.com/devslane/nextjs-redux-tailwind-boilerplate/pull/2#discussion_r830929920)

2022-03-21 10:35 UTC, madhav-devslane commented
Done changes @kush-prof sir

2022-03-21 10:41 UTC, kush-prof approved these changes

2022-03-30 06:54 UTC, kush-prof approved these changes

2022-03-30 06:54 UTC, merged